### ISSUE TITLE
As an user, I want to see my old tasks when i re-open the app in order to continue using my to-do list

### ISSUE THREAD

**Issue by linhhonblade** [linhhonblade/USTH-SE-2019#16]

**Comment by linhhonblade** [comment]
- [x] I

- [x] N

- [x] V

- [x] E

- [x] S

- [x] T

**Comment by dattnguyenn** [comment]
- [x] choose the design pattern [link graph](https://github.com/linhhonblade/USTH-SE-2019/blob/todo/todo/doc/designpattern.pdf) and [link theory](https://courses.edx.org/courses/course-v1:UBCx+SoftEng1x+1T2018/courseware/7d0289438e6a4d6491f2b0adbc48763a/ba2a508c074840bca101d4d010d5c8c2/1?activate_block_id=block-v1%3AUBCx%2BSoftEng1x%2B1T2018%2Btype%40vertical%2Bblock%4067d8c851d0de4be693d14ed493b99af6)
- [x] Store data using textfile [link code](https://github.com/linhhonblade/USTH-SE-2019/commit/5353f9dba9483a05f297365c61caf168a45b6231) 
- [x] Store data using h2 database [link code](https://github.com/linhhonblade/USTH-SE-2019/commit/879bbed7d137b877341ed5bd9bc1ffd6a73c8325)
- [x] Advantages of database over textfile [link](https://github.com/linhhonblade/USTH-SE-2019/blob/todo/todo/doc/DatabaseAdvantages.txt)
=> Choose h2 database
- [x] Add library for h2 database and demo for database implementation 
 + Link to commit :[commit](https://github.com/linhhonblade/USTH-SE-2019/commit/879bbed7d137b877341ed5bd9bc1ffd6a73c8325)
 + Link to demo : [demo](https://github.com/linhhonblade/USTH-SE-2019/commit/41f85667af98cc236d377a3f9f4553a189c99ae5)
 + How to run demo : [README.md](https://github.com/linhhonblade/USTH-SE-2019/blob/todo/todo/README.md)
- [x] h2 database manual test [link test](https://github.com/linhhonblade/USTH-SE-2019/blob/todo/todo/doc/MANUAL%20TEST%20FOR%20DATABASE%E2%80%A6.pdf)
- [x] Using Code Smells (Sonarlint extensions powered by IntelliJ) to see all the problems of the code [link theory](https://courses.edx.org/courses/course-v1:UBCx+SoftEng1x+1T2018/courseware/a58ebf5981e4464c93bccdbc69269898/9261731c1c11441ca017720dd5e14c77/1?activate_block_id=block-v1%3AUBCx%2BSoftEng1x%2B1T2018%2Btype%40vertical%2Bblock%40aba0b44511bf4bd9890b997f5c1ec803)
  For example 
    - Code Smells Within Classes
      + Comment
      + Long Method
    - Code Smells Between Classes
      + Different Interfaces
      + Primitive Obsession
- [x] Refactor code to make it looks neatly
- [x] check the result with the teammate
